### PR TITLE
Fix setting spec of a resource from other resource

### PR DESCRIPTION
**Pull request by leelavg**
ref: https://github.com/kr8s-org/kr8s/pull/401#discussion_r1634860377

### CODE REVIEW

**Comment by leelavg** [comment]
Works at 786a390 and fails at e2b04bc. Will take sometime to get comfortable w/ tools used in the project, will revisit to find the issue.

**Comment by jacobtomlinson** [comment]
Thanks for this, it's really helpful to have a failing test like this. I've made some changes to the getter/setter and also made sure we only use the property throughout. I just pushed 5928daa onto this PR so I can get it merged in.

**Comment by leelavg** [comment]
> I've made some changes to the getter/setter and also made sure we only use the property throughout.
- ya, seems we can now reason about the flow. I still need to figure how your test worked when `raw` was returing a new dict but then the update to this dict still sticked to the object.

**Comment by jacobtomlinson** [comment]
My test passed because I was modifying objects that are nested within and so the pointer ends up pointing to the same dict even though it has been unwrapped and updated into a new dict. Your test failed because you're modifying the top level key.

Here's a toy example

```python
class Foo:

    def __init__(self):
        self._data = {"inner": {"hello": "world"}}

    @property
    def data(self):
        d = {}  # Create a new dict
        d.update(**self._data)  # Copy all the keys and their value pointers into the new dict
        return d

    @data.setter
    def data(self, value):
        self._data = value
```

```python
f = Foo()

id(f.data) == id(f._data)  # False
id(f.data["inner"]) == id(f._data["inner"])  # True
```

Whereas if we just return `self._data` directly in the property then `id(f.data) == id(f._data)` is `True`.

**Comment by leelavg** [comment]
Ah! right, thanks, missed it. `.update` isn't a deep copy.

**Pull request merged**
